# Generated by Django 3.2.7 on 2021-10-28 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Question',
        ),
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question_answer.answer'),
            preserve_default=False,
        ),
    ]
